### ISSUE TITLE
cannot make alert appear in top-right

### ISSUE THREAD

**Issue by krispayne** [JAMFSupport/jHelper-GUI#4]
I downloaded this to test it out and noticed that I could make the alert appear in all the other optional locations, however not in the top right corner.

When clicking "Launch Helper" with the position set to "Upper Right" The alert shows up in the center of the screen. Also, when selecting "Center" It shows up in the center on the horizontally, but about 1/4 of the way down from the top vertically.

![screen shot 2016-10-13 at 4 46 26 pm](https://cloud.githubusercontent.com/assets/70580/19371039/ca3bb854-9164-11e6-8e9d-102bc52a701d.png)

**Comment by jordanpatrick** [comment]
Are you using multiple monitors? I know that the "jamfHelper" binary does not handle being run from a secondary monitor very well. I'm seeing that if I use the "Launch Helper" or run the script from Terminal on a secondary monitor the Upper Right option doesn't work, and the other options are off in position.

As for the Center option, I'm seeing the same thing with that even on the main display. It is centered horizontally but not vertically. 

In either case it looks like these are problems with the "jamfHelper" binary, so I won't be able to directly do anything to change this. I'll do some more testing though.

**Comment by krispayne** [comment]
Yep, using an external monitor with my laptop. I didn't think to run the CLI to test either, so that makes sense that it would be an error in the `jamfhelper`, not the GUI app.

**Comment by jordanpatrick** [comment]
Sounds good! I'll close out this issue then since it looks like it's a binary limitation.
