### ISSUE TITLE
Great tool. Easy to fix problem? Xcode 8.1 & Swift 3

### ISSUE THREAD

**Issue by GitStoph** [JAMFSupport/jHelper-GUI#6]
![image](https://cloud.githubusercontent.com/assets/20820226/19976268/0f3d626e-a1bd-11e6-90f7-654d6c65ce9f.png)
Before any conversion.
![image](https://cloud.githubusercontent.com/assets/20820226/19976356/6d8b496c-a1bd-11e6-95aa-03f2b80321f2.png)
After letting it make the "recommended" changes/optimization.
I have no swift skills. Interested in trying the tool. Help please!
Thanks-

**Comment by jordanpatrick** [comment]
Hey! I'm going through a major rewrite of the code currently (and a renaming) so there are a few things likely not working in the current source code.

I'd recommend heading here: https://github.com/JAMFSupport/jHelper-GUI/releases  and downloading the latest compiled ".app" version of the program. Most everything should be working in that latest complied release.

**Comment by jordanpatrick** [comment]
New version now has support for Swift 3 and the latest Xcode
